name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  ferry: ^0.16.0+1
  # path: ^1.8.0

dev_dependencies:
  ferry_generator_freezed:
    path: ../../ferry_generator_freezed
  build_runner:
  lints: ^3.0.0
  test: ^1.24.0
